project_name: terminus-cli
builds:
  - env:
      - CGO_ENABLED=0
    binary: terminus-cli
    main: ./cmd/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: arm
    ldflags:
      - s
      - w
      - -X bytetrade.io/web3os/installer/version.VERSION={{ .Version }}
dist: ./output
archives:
  - id: terminus-cli
    name_template: "{{ .ProjectName }}-v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      linux: linux
      amd64: amd64
      arm: arm64
checksum:
  name_template: "checksums.txt"
changelog:
  skip: true
