version: 2
project_name: olares-cli
builds:
  - env:
      - CGO_ENABLED=0
    binary: olares-cli
    main: ./cmd/main.go
    goos:
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -s
      - -w
      - -X bytetrade.io/web3os/installer/version.VERSION={{ .Version }}
dist: ./output
archives:
  - id: olares-cli
    name_template: "{{ .ProjectName }}-v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
