name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.4

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.1.0
        with:
          distribution: goreleaser
          version: v1.18.2
          args: release --clean

      - name: Upload to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cli-upload
          path: |
            ./scripts/create-cert.ps1
            ./output/*

  signing: # ! remote runner
    runs-on: windows-latest
    needs: [goreleaser]

    steps:
      - name: Download Cli
        uses: actions/download-artifact@v3
        with:
          name: cli-upload
          path: ./

      - name: "Signing"
        run: |
          .\scripts\create-cert.ps1;

      - name: "Show"
        run: |
          Get-ChildItem -Path .\ -Recurse -File

      - name: "Upload Signed"
        uses: actions/upload-artifact@v3
        with:
          name: signed
          path: |
            ./output/*

  release:
    runs-on: ubuntu-latest
    needs: [signing]

    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: signed
          path: ./

      - name: "Show"
        run: |
          sudo apt update && sudo apt install tree -y && tree ./
