name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.4

      - name: Install coscmd
        run: pip install coscmd

      - name: Configure coscmd
        env:
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          COS_BUCKET: ${{ secrets.COS_BUCKET }}
          COS_REGION: ${{ secrets.COS_REGION }}
          END_POINT: ${{ secrets.END_POINT }}
        run: |
          coscmd config -m 10 -p 10 -a $TENCENT_SECRET_ID \
                        -s $TENCENT_SECRET_KEY \
                        -b $COS_BUCKET \
                        -r $COS_REGION

      - name: Install x86_64 cross-compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install ARM cross-compiler
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.1.0
        with:
          distribution: goreleaser
          version: v1.18.2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-1"
        run: |
          for ext in tar.gz txt; do
            cd output && for file in *.$ext; do
              if [ -f "$file" ]; then
                aws s3 cp "$file" s3://zhangliang-s3-test/test2/$file
                # coscmd upload $file /$file
              fi
            done
          done
