name: Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Tags"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.4

      - name: Install x86_64 cross-compiler
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Run GoReleaser
        uses: softprops/action-gh-release@v1
        with:
          distribution: goreleaser
          version: v1.18.2
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ github.event.inputs.tag }}
